### ISSUE TITLE
Web App not working Correctly

### ISSUE THREAD

**Issue by Notplayingallday383** [cohenerickson/Velocity#22] opened 2023-04-27 17:37 UTC
Hi, Recently I have noticed that the PWA Web App of Velocity does not work when you launch it from the ChromeOS Launcher and I have found out why. Its because it starts at /index.html which generates a 404 error/white screen
I think this should fix it but idk
`{
  "name": "Velocity",
  "short_name": "Velocity",
  "description": "A fully featured web browser built using web technologies.",
  "icons": [
    {
      "src": "icons/32.png",
      "sizes": "32x32",
      "type": "image/png"
    },
    {
      "src": "icons/512.png",
      "sizes": "512x512",
      "type": "image/png"
    },
    {
      "src": "icons/touch.png",
      "sizes": "512x512",
      "type": "image/png",
      "purpose": "maskable"
    }
  ],
  "start_url": "/",
  "display": "fullscreen",
  "theme_color": "#1c1b22",
  "background_color": "#1c1b22",
  "display_override": ["window-controls-overlay"]
}`

**Comment by glitch128** [comment] 2023-04-27 17:56
it already has, he just hasn't pulled the changes to the VPS. I was the one to create the pull request to fix that

**Comment by cohenerickson** [comment] 2023-04-27 19:14
Duplicate of #14 and fixed in #16

**Closed** 2023-04-27 19:14 UTC

**Comment by glitch128** [comment] 2023-04-27 20:17
hey, I feel like this shouldn't be closed until the changes have actually been pulled to the website

**Comment by cohenerickson** [comment] 2023-04-27 20:42
As I see it, the issue has been resolved.
